version: '3.4'

services:
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  transaction-app:
    image: transaction-app
    environment:
      - "TZ=America/Sao_Paulo"
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    command: ["java", "-jar", "-Dspring.data.mongodb.host=mongo", "/opt/transaction-app/transaction-app.jar"]