version: '3.4'

services:
  transaction-app:
    image: transaction-app
    environment:
      - "TZ=America/Sao_Paulo"
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/opt/transaction-app/transaction-app.jar"]